name: spatial_measure
description: A mobile 3D scanning and measurement tool.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  camera: ^0.10.5+2
  ar_flutter_plugin: ^0.7.3
  path_provider: ^2.0.15
  share_plus: ^7.0.0
  permission_handler: ^10.3.0
  model_viewer_plus: ^1.5.0
  pdf: ^3.10.1
  printing: ^5.10.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
