name: google_docs_app
description: "A Google Docs mobile application built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI and Material Design
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.1

  # Rich Text Editing
  flutter_quill: ^11.4.2

  # Navigation
  go_router: ^12.1.3

  # HTTP and API
  http: ^1.1.2

  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

  # File Operations
  path_provider: ^2.1.1
  file_picker: ^6.1.1
  share_plus: ^7.2.1

  # Image and Media
  image_picker: ^1.0.4

  # PDF and Document Export
  pdf: ^3.10.7

  # Utilities
  uuid: ^4.2.1
  connectivity_plus: ^5.0.2

  # Animations
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/templates/
  #   - assets/animations/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Roboto-Italic.ttf
  #         style: italic
