name: google_maps_app
description: A comprehensive Google Maps-like mobile application built with Flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI and State Management
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  
  # Maps and Location
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # HTTP and API
  http: ^1.1.0
  dio: ^5.3.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Utilities
  uuid: ^4.1.0
  intl: ^0.18.1
  url_launcher: ^6.2.1
  
  # Permissions
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
