name: conecte_sus_app
description: "Conecte SUS - Official digital health platform for Brazil's Unified Health System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.2
  
  # HTTP requests
  http: ^1.2.1
  
  # Local Storage
  shared_preferences: ^2.2.3
  
  # QR Code generation
  qr_flutter: ^4.1.0
  
  # PDF generation
  pdf: ^3.10.8
  printing: ^5.12.0
  
  # URL launcher for Gov.br authentication
  url_launcher: ^6.2.6
  
  # Date formatting
  intl: ^0.19.0
  
  # Icons
  flutter_svg: ^2.0.10+1
  
  # File picker and sharing
  file_picker: ^8.0.0+1
  share_plus: ^7.2.2
  
  # Path provider for file operations
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
