name: teams_app
description: "Microsoft Teams mobile application built with Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  
  # State Management
  provider: ^6.1.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  
  # Navigation
  go_router: ^14.2.7
  
  # HTTP & API
  http: ^1.2.2
  dio: ^5.7.0
  
  # Local Storage
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Authentication
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  google_sign_in: ^6.2.1
  
  # Real-time Communication
  socket_io_client: ^2.0.3+1
  web_socket_channel: ^3.0.1
  
  # Media & Files
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  
  # Video & Audio
  camera: ^0.11.0+2
  video_player: ^2.9.1
  audioplayers: ^6.1.0
  permission_handler: ^11.3.1
  
  # Calendar & Time
  table_calendar: ^3.1.2
  intl: ^0.19.0
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  firebase_messaging: ^15.1.3
  
  # Utils
  uuid: ^4.5.1
  timeago: ^3.7.0
  url_launcher: ^6.3.1
  share_plus: ^10.0.2
  path_provider: ^2.1.4
  
  # Animations
  lottie: ^3.1.2
  flutter_staggered_animations: ^1.1.1
  
  # Emoji & Rich Text
  emoji_picker_flutter: ^4.3.0
  flutter_mentions: ^2.0.1
  
  # Search
  flutter_typeahead: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
