name: canva_mobile_app
description: "A comprehensive mobile design platform inspired by Canva, featuring template-driven workflows, drag-and-drop editing, AI-powered tools, and collaborative design capabilities."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^4.2.1
  flutter_speed_dial: ^7.0.0
  
  # State Management
  provider: ^6.1.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  
  # Image & Media Processing
  image_picker: ^1.1.2
  image: ^4.2.0
  photo_view: ^0.15.0
  flutter_colorpicker: ^1.1.0
  image_cropper: ^8.0.2
  
  # Canvas & Drawing
  flutter_signature_pad: ^3.0.1
  
  # File Operations
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  permission_handler: ^11.3.1
  file_picker: ^8.1.2
  
  # Network & API
  http: ^1.2.2
  dio: ^5.7.0
  cached_network_image: ^3.4.1
  
  # Storage & Database
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Animations & Effects
  lottie: ^3.1.2
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  
  # Utilities
  uuid: ^4.5.1
  intl: ^0.19.0
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  
  # Social Features
  url_launcher: ^6.3.1
  
  # Video Processing
  video_player: ^2.9.1
  video_thumbnail: ^0.5.3
  
  # Text & Fonts
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/templates/
    - assets/fonts/
    - assets/animations/
    - assets/sample_designs/
    - assets/stock_photos/
    - assets/stock_videos/
    - assets/audio/

  # Custom fonts
  fonts:
    - family: Canva
      fonts:
        - asset: assets/fonts/Canva-Regular.ttf
        - asset: assets/fonts/Canva-Bold.ttf
          weight: 700
        - asset: assets/fonts/Canva-Light.ttf
          weight: 300
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
