name: color_by_number_app
description: "A relaxing color-by-number mobile application for digital art therapy."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.2
  
  # Navigation
  go_router: ^14.2.7
  
  # Local Storage
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  path: ^1.9.0
  
  # Image Processing & Canvas
  flutter_svg: ^2.0.10+1
  image: ^4.2.0
  
  # Gestures & Animations
  flutter_staggered_animations: ^1.1.1
  
  # Social Sharing
  share_plus: ^9.0.0
  
  # File System
  path_provider: ^2.1.3
  
  # Permissions
  permission_handler: ^11.3.1
  
  # JSON Serialization
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/coloring_pages/
    - assets/icons/
    - data/

  # Fonts
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
