name: uber_app
description: "A comprehensive Uber-like ride-hailing mobile application built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296

  # State Management
  provider: ^6.1.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1

  # Maps & Location
  google_maps_flutter: ^2.6.1
  google_maps_flutter_web: ^0.5.7
  location: ^5.0.3
  geolocator: ^10.1.1
  geocoding: ^3.0.0

  # HTTP & API
  http: ^1.2.1
  dio: ^5.4.3+1

  # Navigation
  go_router: ^14.2.0

  # Storage & Persistence
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utilities
  intl: ^0.19.0
  uuid: ^4.4.0
  url_launcher: ^6.2.6
  image_picker: ^1.1.2
  equatable: ^2.0.5

  # Animations & UI Enhancements
  lottie: ^3.1.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1

  # Permissions
  permission_handler: ^11.3.1

  # Real-time Communication
  socket_io_client: ^2.0.3+1

  # Payment Integration (Mock)
  flutter_credit_card: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  # fonts:
  #   - family: UberMove
  #     fonts:
  #       - asset: assets/fonts/UberMove-Regular.ttf
  #       - asset: assets/fonts/UberMove-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/UberMove-Bold.ttf
  #         weight: 700
