name: blink_fitness_app
description: "Blink Fitness mobile app - Your digital gym companion"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.2
  
  # Navigation
  go_router: ^14.2.7
  
  # HTTP requests
  http: ^1.2.2
  dio: ^5.7.0
  
  # Local Storage
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Authentication
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  
  # Barcode/QR Code
  qr_flutter: ^4.1.0
  barcode_widget: ^2.0.3
  mobile_scanner: ^5.2.3
  
  # Image handling
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  
  # Video player
  video_player: ^2.9.2
  chewie: ^1.8.5
  
  # Health integration
  health: ^10.2.0
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  
  # Loading and animations
  shimmer: ^3.0.0
  lottie: ^3.1.2
  
  # Icons
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/videos/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
