name: paypal_app
description: "PayPal Mobile App - A comprehensive digital wallet and financial hub"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.2
  
  # Navigation
  go_router: ^14.2.7
  
  # HTTP Requests
  http: ^1.2.2
  dio: ^5.7.0
  
  # Local Storage
  shared_preferences: ^2.3.2
  
  # QR Code
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  
  # Permissions
  permission_handler: ^11.3.1
  
  # Icons
  font_awesome_flutter: ^10.7.0
  
  # Image handling
  cached_network_image: ^3.4.1
  
  # Animations
  lottie: ^3.1.2
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.5.1
  
  # Biometric Authentication
  local_auth: ^2.3.0
  
  # Device Info
  device_info_plus: ^10.1.2
  
  # Package Info
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  # fonts:
  #   - family: PayPalSans
  #     fonts:
  #       - asset: assets/fonts/PayPalSans-Regular.ttf
  #       - asset: assets/fonts/PayPalSans-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/PayPalSans-Bold.ttf
  #         weight: 700
