name: waze_app
description: A community-powered traffic and navigation app inspired by Waze.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and State Management
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  equatable: ^2.0.5

  # Maps and Location
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_polyline_points: ^2.0.0

  # Navigation and Routing
  go_router: ^12.1.3
  flutter_compass: ^0.7.0

  # HTTP and API
  http: ^1.1.2
  dio: ^5.4.0

  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3

  # Audio and Media
  audioplayers: ^5.2.1
  flutter_tts: ^3.8.5
  just_audio: ^0.9.36

  # Permissions
  permission_handler: ^11.1.0

  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0

  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1
  url_launcher: ^6.2.2
  share_plus: ^7.2.1

  # Real-time features
  web_socket_channel: ^2.4.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  firebase_database: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
