name: whatsapp_business
description: "WhatsApp Business - A professional messaging platform for small and medium businesses"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.2
  
  # Navigation
  go_router: ^14.2.7
  
  # Storage
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  path: ^1.9.0
  
  # Image handling
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  
  # Date and time
  intl: ^0.19.0
  
  # HTTP requests
  http: ^1.2.2
  
  # File handling
  path_provider: ^2.1.3
  
  # QR Code generation
  qr_flutter: ^4.1.0
  
  # URL launcher
  url_launcher: ^6.3.0
  
  # Permissions
  permission_handler: ^11.3.1
  
  # UUID generation
  uuid: ^4.4.2
  
  # JSON serialization
  json_annotation: ^4.9.0
  
  # Audio recording and playback
  audioplayers: ^6.0.0
  record: ^5.1.2
  
  # Video player
  video_player: ^2.8.6
  
  # File picker
  file_picker: ^8.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  # Code generation
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
