name: booking_app
description: A comprehensive travel booking application similar to Booking.com
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^12.1.3
  
  # HTTP requests
  http: ^1.1.2
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Date handling
  intl: ^0.19.0
  
  # Image handling
  cached_network_image: ^3.3.1
  
  # Icons
  cupertino_icons: ^1.0.6
  
  # UI Components
  flutter_rating_bar: ^4.0.1
  
  # Maps (for property locations)
  google_maps_flutter: ^2.5.3
  
  # Image picker for user profile
  image_picker: ^1.0.7
  
  # UUID for generating IDs
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
