name: betano_app
description: "Betano - Sports Betting & Casino App for Brazil"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^12.1.3
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI Components
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_staggered_grid_view: ^0.7.0
  
  # Authentication & Security
  crypto: ^3.0.3
  local_auth: ^2.1.7
  
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.2
  image_picker: ^1.0.4
  permission_handler: ^11.1.0
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  
  # Video & Streaming
  video_player: ^2.8.1
  
  # QR Code
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  
  # Charts & Graphs
  fl_chart: ^0.65.0
  
  # Animation
  lottie: ^2.7.0
  
  # WebView
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
