name: audible_app
description: "A comprehensive audio entertainment platform for audiobooks, podcasts, and exclusive content."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296

  # State Management
  provider: ^6.1.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^14.2.7

  # Audio Playback
  just_audio: ^0.9.40
  audio_service: ^0.18.15
  just_audio_background: ^0.0.1-beta.13

  # HTTP and API
  http: ^1.2.2
  dio: ^5.7.0

  # Local Storage
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4

  # Image Handling
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2

  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  equatable: ^2.0.5
  json_annotation: ^4.9.0

  # UI Components
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  smooth_page_indicator: ^1.2.0
  flutter_slidable: ^3.1.1

  # Permissions
  permission_handler: ^11.3.1

  # Device Info
  device_info_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/

  # Fonts (using system fonts for now)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
