name: capcut_app
description: "A professional video editing mobile application built with Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  flutter_riverpod: ^2.5.1

  # Video & Media
  video_player: ^2.8.6
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  file_picker: ^8.0.0+1
  ffmpeg_kit_flutter: ^6.0.3
  video_thumbnail: ^0.5.3
  
  # Audio
  audioplayers: ^6.0.0
  just_audio: ^0.9.37
  audio_waveforms: ^1.0.5
  
  # Storage & File Management
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  
  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  flutter_colorpicker: ^1.0.3
  flutter_xlider: ^3.5.0
  timeline_tile: ^2.0.0
  
  # Animations & Effects
  lottie: ^3.1.0
  flutter_animate: ^4.5.0
  
  # Networking & API
  http: ^1.2.0
  dio: ^5.4.1
  
  # Utilities
  uuid: ^4.3.3
  intl: ^0.19.0
  equatable: ^2.0.5
  
  # AI & ML (for future features)
  tflite_flutter: ^0.10.4
  
  # Social Sharing
  share_plus: ^7.2.2
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/audio/
  #   - assets/templates/
  #   - assets/effects/
  #   - assets/fonts/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Roboto-Light.ttf
  #         weight: 300
