name: threads_app
description: A Threads-like social media app for text-based conversations
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  timeago: ^3.6.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.1
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  uuid: ^4.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
