name: google_home_app
description: "A comprehensive Google Home mobile application for smart home control and automation."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # UI Components
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  
  # Navigation
  go_router: ^12.1.3
  
  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  
  # HTTP and API
  http: ^1.1.2
  
  # Image handling
  cached_network_image: ^3.3.0
  
  # Animations
  lottie: ^2.7.0
  
  # Device info
  device_info_plus: ^9.1.1
  
  # Permissions
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  # fonts:
  #   - family: GoogleSans
  #     fonts:
  #       - asset: assets/fonts/GoogleSans-Regular.ttf
  #       - asset: assets/fonts/GoogleSans-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/GoogleSans-Bold.ttf
  #         weight: 700
