name: temu_app
description: A Temu-like e-commerce mobile application with gamification features.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # HTTP requests
  http: ^1.1.0
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Image handling
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  
  # UI Components
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0
  
  # Icons
  cupertino_icons: ^1.0.2
  
  # Animations
  lottie: ^2.7.0
  
  # Utils
  intl: ^0.18.1
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
